# snippets for bash

[[tagGroup]]
name = "Docker"
tags = "Docker,イメージ,コンテナ,一覧"
description = ""

# [[tagGroup]]
# name = "操作"
# tags = "移動,コピー,開く,作成,変更,削除"
# description = ""

# [[tagGroup]]
# name = "ファイル"
# tags = "ファイル,フォルダ,ルート,カレント,ディレクトリ,書,読"
# description = ""

[[tagGroup]]
name = "その他"
tags = "一覧,待つ,検索,文字,変数,サブルーチン,コメント"
description = ""

# ----------------------------------------------------------------
[[snippets]]
title = "nohupによるコマンドのバックグラウンド実行"
icon = "code"
description = """
「コマンド」の出力はnohup.outにリダイレクトして、&以降のコマンドを並列実行する。
"""
code = """
nohup コマンド &
"""

[[snippets]]
title = "イメージ一覧を表示[docker]"
code = """docker image ls"""

[[snippets]]
title = "コンテナ一覧を表示[docker]"
code = """docker ps -a"""

[[snippets]]
title = "コンテナ全削除[docker]"
description = "stopしたコンテナしか削除できないので、まずコンテナを停止させてから、削除する。"
code = """
# コンテナ全停止
sudo docker stop $(sudo docker ps -q)
# コンテナ全削除
sudo docker rm $(sudo docker ps -a -q)
"""

[[snippets]]
title = "イメージ全削除[docker]"
code = """sudo docker rmi $(sudo docker images -q)"""

[[snippets]]
title = "コンテナ全停止[docker]"
code = """sudo docker stop $(sudo docker ps -q)"""

[[snippets]]
title = "コンテナIDを指定して停止・削除[docker]"
code = """TMP=containerId && sudo docker stop $TMP && sudo docker rm $TMP"""


