# snippets for python

[[tagGroup]]
name = "操作"
tags = "移動,コピー,開く,作成,変更,削除,ソート"
[[tagGroup]]
name = "その他"
tags = "debug,pandas,jupyter"

[[snippets]]
title = "実行中一時停止してデバッガーを起動"
icon = "unknown"
description = "実行中一時停止してデバッガーを起動"
code = "from IPython.core.debugger import Pdb; Pdb().set_trace()"


[[snippets]]
title = "実行エラー時に一時停止してデバッガーを起動するように設定"
icon = "unknown"
description = "実行エラー時に一時停止してデバッガーを起動するように設定 #debug"
code = "%pdb on"

[[snippets]]
title = "実行エラー時に一時停止してデバッガーを起動する設定を解除"
icon = "unknown"
description = "実行中一時停止してデバッガーを起動  #debug"
code = "%pdb off"

[[snippets]]
title = "pandas メソッドチェインで列追加"
icon = "unknown"
description = ""
code = "df.assign(key_name='value')"

[[snippets]]
title = "集約して、カラムごとに異なる集約をする[pandas]"
code = "df.groupby('name').agg({'A':[np.sum, np.mean], 'B':[np.sum, np.min]})"

[[snippets]]
title = "指定した関数で集計し、指定したカラム名で追加したDFを返す"
code = """df.agg([('最小値','min'),('最大値', 'max')])"""

[[snippets]]
title = "ローカルwebサーバを立ち上げ"
code = """python -m http.server 8000"""

[[snippets]]
title = "変数の存在チェック"
description = "例）appという名前の変数が存在するか確認"
code = """if 'app' in locals(): True"""

# -------------------------- Pandas document ------------------------------------

[[snippets]]
title = "pandas.read_pickle#"
description = """Load pickled pandas object (or any object) from file.Notesread_pickle is only guaranteed to be backwards compatible to pandas 0.20.3
provided the object was serialized with to_pickle.Examples"""
url = "https://pandas.pydata.org/docs/reference/api/pandas.read_pickle.html"
code = """>>> original_df = pd.DataFrame(
...     {"foo": range(5), "bar": range(5, 10)}
...    )  
>>> original_df  
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9
>>> pd.to_pickle(original_df, "./dummy.pkl")  

>>> unpickled_df = pd.read_pickle("./dummy.pkl")  
>>> unpickled_df  
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9"""

[[snippets]]
title = "pandas.DataFrame.to_pickle#"
description = """Pickle (serialize) object to file.Examples"""
url = "https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html"
code = """>>> original_df = pd.DataFrame({"foo": range(5), "bar": range(5, 10)})  
>>> original_df  
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9
>>> original_df.to_pickle("./dummy.pkl")  

>>> unpickled_df = pd.read_pickle("./dummy.pkl")  
>>> unpickled_df  
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9"""

[[snippets]]
title = "pandas.read_table#"
description = """Read general delimited file into DataFrame.Also supports optionally iterating or breaking of the file
into chunks.Additional help can be found in the online docs for
IO Tools.Examples"""
url = "https://pandas.pydata.org/docs/reference/api/pandas.read_table.html"
code = """>>> pd.read_table('data.csv')  """

[[snippets]]
title = "pandas.read_csv#"
description = """Read a comma-separated values (csv) file into DataFrame.Also supports optionally iterating or breaking of the file
into chunks.Additional help can be found in the online docs for
IO Tools.Examples"""
url = "https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html"
code = """>>> pd.read_csv('data.csv')  """

[[snippets]]
title = "[Jupyter]pyファイルの自動再読み込みなど"
description = """
%matplotlib inline : グラフをノートブック内に表示
%reload_ext autoreload : 自動リロード機能を有効化。モジュールの変更を自動的に反映させる。
%autoreload 2 : 自動リロード機能のモード設定。（2 : 変更されたすべてのモジュールを毎回リロード）
"""
code = """
%matplotlib inline
%reload_ext autoreload
%autoreload 2
"""
