# snippets for rust

[[tagGroup]]
name = "操作"
tags = "新規"

[[tagGroup]]
name = "その他"
tags = "cargo,プロジェクト"


[[snippets]]
title = "新規プロジェクトを作成"
description = """
hello_world : プロジェクト名
"""
code = """
cargo new hello_world
"""

[[snippets]]
title = "rustライブラリをWebAssemblyにコンパイルしてnpmに発行する"
description = """
https://developer.mozilla.org/ja/docs/WebAssembly/Rust_to_wasm
"""
url = ""
code = """
# install
cargo install wasm-pack
# create
cargo new --lib hello-wasm
# build
wasm-pack build --target web
# publish npm
npm publish pkg

"""
thumbnail = ""
