# snippets for bat

[[tagGroup]]
name = "構文"
tags = "変数,配列,辞書,for,サブルーチン,コメント"
# color="#ccc"
description = "基本構文"

[[tagGroup]]
name = "操作"
tags = "移動,コピー,開く,作成,変更,削除"
# color="#ccc"
description = ""

[[tagGroup]]
name = "Vue"
tags = "Vue,ディレクティブ,reactive"
# color="#ccc"
description = ""

[[tagGroup]]
name = "その他"
tags = "ファイル,フォルダ,書,読,待つ,検索"
# color="#ccc"


[[snippets]]
title = "WEBからファイル取得して文字列を処理"
icon = "unknown"
description = """
WEBからファイル取得して文字列を処理
"""
code = """
fetch(_{url}_)
    .then(response => response.text())
    .then(input => {
        _{文字列処理}_
    });
"""

[[snippets]]
title = "tomlファイルを解析"
icon = "unknown"
description = """
tomlファイルを解析

事前準備　`import toml from "toml";`
"""
code = """
try {
    toml.parse(_{TOML文字列}_);
} catch (e) { console.error(`Parse error on ${tomlPath}. ${e}`); }
"""

[[snippets]]
title = "reactiveな配列の定義"
icon = "unknown"
description = """
reactiveな配列の定義 #vue
"""
code = """
var _{変数名}_ = reactive([
{
    _{キー: "値", ...}_
},
]);
"""

[[snippets]]
title = "[vue]v-forとv-ifでinput/div混合したブロックを作成"
icon = "unknown"
description = """
v-forとv-ifディレクティブでinput/div混合したブロックを作成　#vue

item.isVariable　：　trueならテキストボックスで編集可能にする
item.code　：　表示文字列
"""
code = """
<template v-for="(item, i) in _{コレクション}_" v-bind:key="i">
<input
    type="text"
    v-if="item.isVariable"
    v-model="item.code"
    class="code-item"
/>
<div v-else class="code-item">{{ item.code }}</div>
</template>
"""



[[snippets]]
title = "[vue]v-forディレクティブの例：ボタンをたくさん作成"
icon = "unknown"
description = """
v-forでボタンをたくさん作成 #vue
"""
code = """
<button
class="search-tag"
v-for="(text, index) in _{コレクション}_"
v-bind:key="index"
@click="
    _{アクション:search(text)}_;
"
>
{{ text }}
</button>
"""

[[snippets]]
title = "[vue+TS]マークダウンをhtmlに変換"
icon = "unknown"
description = """
リポジトリ　https://github.com/markedjs/marked

インストール
```
npm install marked
npm install @types/marked # For TypeScript projects
```
#vue
"""
code = """
<script>
import * as marked from 'marked';

function md2html(mdstr:string) {
    // markdownの改行はそのまま反映するために、末尾に「  」を追加
    return marked.marked(mdstr.replace(/\r?\n/g, "  \n"), { sanitize: true });
}
</script>

<template>
<div class="snippet-common-description" >
    <div v-html="md2html(_{MarkDown文字列}_)" />
</div>
</template>
"""


[[snippets]]
title = "[TS]foreach (for ... of ...)"
icon = "unknown"
description = """
Pythonのようなfor in ではなく、for ofを使う。
for i in 配列　はiに指数が代入されてしまう。
"""
code = """
for (let s of _{配列:str.split("\r\n")}_) {
    _{処理:console.log(s)}_;
}
"""

[[snippets]]
title = "貼り付け時に実行する関数を指定"
description = """

"""
url = ""
code = """
<textarea @paste="onPaste"></textarea>

"""
thumbnail = ""

[[snippets]]
title = "マウスオーバーしたら親要素にオーバーレイ表示[vue3+sfc+setup]"
code = """
<script>
var showSnippet = ref(null);
</script>
<template>
<li
  v-show="item.visible"
  v-on:mouseover="showSnippet = item"
  v-on:mouseleave="showSnippet = null"
>
    <div v-if="showSnippet == item">
</li>
</template>
"""
thumbnail = "data:image/gif;base64,R0lGODlh+gCdAIAAAAAAAAAAACH5BAgAAAAALAAAAAD6AJ0Ag0pKTJudn8C8t8rOz9jY2Njg2NrRytvY0Nzn6+Dg3+jo6Ojo8Onw7/Do6PDw8Pj4+AT/0LVHq63o6s117mDohGRpnsh4nsO6Mi5qSeUXk/bdqXrvp75OK8iBETc5Gu6IZF54zigS6hxKH8ZrcrK8PnJOqlcKvFqlWfKMGwI73Ufx+C0nnqPp6Nah6Pv/gIGCg4SFhoeIiYqLjI2Oj5CKDhJ8kZaXmJmam5ydhg4IoQiepKWNBwOmqquXKQ2VlwkAqYECAwmZBAG0fQMBfgIBwrt+ssPDCAnEiwIAggC/vce4s30HALh+BtgHw9kKwcO8rOR/k6/a0LKz6wEA77Pw6gQD0APNqQnN8sny8LcDAgr81mfdKAXQ3PnxB0CAAH3Q/CHA90cZQ2wXG2Z0J6+eQ4a4//ZxxDZSXrRyKBWcg7XuGrRmwRo6dMlxnb9f23aF6+Xw46xtN//Ug7ZQmLM++/y5fOdzIoCDBcPBE2Yx4bsASf3ZfOcxZkKsCC5SK0k0JcqVf5hOneUugVuXBN4hZRvR6cgABBUY9KPzqd6q46wCAxDX3TYCcRk6hfptHaC2ifmaRLCUa0OI/uqR3WrS7FlKf9y5S1r1XeVZYWfBjHjV6Mk+QNPC0yuxmOBmd+G180egme1oFP8k5qpXamuyHslizcpac1DP5NAONj3bHWICcPcZbLvLVzZjFd811k17QG+/1qzuzlnzKu9m2XD3cTeuF3FwGR1aj2dcPOypHA2VGf900YFmmzpXKSCaMENx5OA+FemXoC/wCODHUPXNdRBQFFq2FlO4aYVbU/+95BZz0IyCWTGi6TMafhzZUtpHZE0FFYGlSFcQfRaF1JFJxsT4B1BM4eLgAAe1c+NgKl6FQIAK3JNUPfdg49UvmKlTzJTrPITZKCIN9pACHNLmD0zM3YJiXjh2omObvbA5yC3SwGnnnZi8ieeefPZJip5+BirooJIYSOihiCbaB6CKRimncBk2KmkmOuoTjC3ChHPPcgn4souLbfVEizJ4CWOmPUapZqFex3ia6VS4ZZopZruwtuSkuBaKzo7DJBbjpjq9WBA2vdmiYEP9ABeOhKrxIgv/Aaz6Yt55+gC71Gq2vBTArbl2W8ib4ZQKTgAGLGeLtMrsmA9Vl6YSjosaiXaVjAL0MypRV2qWaTPJhDvMfd4G/K2h4AhgwEOyYhURLqSWqo4yqyJ1yy70XYpVuRUPUxyDwQ5QrpoP+TbiMVg5KPDJgzCK8sosJ1KpWzDHLPPMNNds880456zzzjz37PPPQAct9M2LGprAdUgnrfTSTDft9NNQRy311FRXbfXVWGcNddG76qX112CHLfbYZJdtttJcs3T22my37fbbcCOWdjFx12333XjbPXdBefft99+AT72319fdMy09SAuAmLTXCaO0QLtcZ0vglFdu+eBHFx45/2IBIE1Yb503vrRDuhxeuuWop3435p6zpXCtMQaDdOe0a0Y6VrOHrvruvJvNuuaFWdc5lQ3prktccflSrC7GO97789Br/fvitQt/Xlyki16r8rebvnn04Ie/tUpGI30P6AHR7rjiFJesvuGQA5s99OaZLv79100/teHdJc24+QKx2vzGZjzRoY92isMf/hbFAAU0kG9V45jiznWu4dnCIVLCoOEwOJPJLQ5TCUQMB4slpd5IKSATDCE+4Hcexc3idJ9ToPj6wIAGqi2CsPtXMJRHsuJ9xTVfkd0HA/JCxBRvGLEqmQ/9JUK2hAsmyEteFGUYPhqWb38HHA5h2KKLK/9FZB+aCR48GscW023RKlYZSmFYczHk/cOFRjTPC2NIxejpD2rDoxjzhCctrLjKNX8MXq8AmDT1/Ws5RhHkq8zTPpJZkHshrCP07hg1gdhPcgE5QNMC8jj/FVGSoIQbJaG2wwJSL4BME2LuzBfJULpybaN8mmU6ZxVM0aNKrqHdOwqHqhCe75XAPFssnVbKWJWxc/oxCoWCpzmD4U6ErQymNL82zKUhU49WSR4yl+UefRUOhJr84DTHCbZqKi2P5wtX6boDP8KkT4+LuyQ9dCJPctrTaea0Wh8XlMtjYIowjktVGe9J0Kjls2qQXKclmxWPqczzjfUsqEShRb6uZW7/bMrrY/1Ew7xZctRBqjHlRCd6UKopz4jsu0k8BOQLTBnOhCONaf4qekOMNpJBpwMd6H4o0OJFVKbkLKlOo6kLrljylvWbFifpca4AWhJyXAFqQYV6PFVK9apto2oepYjVrpZNq3L0qli/SlO6TW2r3xurWq8mVOGx76drjSvTqCrXumaNrnbNK9Xwqte+Po2vfg0s2soKQcEalq2EJdxhFyu4xJJvEpCNrGQnS9nKWvaymM2sZjfL2c569rOgDa1oKeuHN432tKhNrWpXy9rWulaypSUYZFPx2tra9ra4zS1rETAAyMa2a+TzxWN1S9ziGve4r31Sb2FhWlD8ArnQ/42udKdr2SelgLmyncQoqMvd7noXt0Vjriig8t3ymve8rfWDK2DRsva6lxAqe698WxZf9ZKCW/NNCX4FRV4ltGEMcCBCHeZAhDJI4Q5OyMMb1lADAHthwAT+AYR7gGAmKJgJW8BAHQJc4AdHWAsT1kGFj3DhI2SYAggoMYeDsOIehPjDLjBwFEZMhBJ3uAL+TTEHWtwDHt/gxTBGAZBdQOMg2JjFDEaxih18hSEHGQdOZsEYjvyDJD8gGBf28Q207IIoP7kDMq7ClJlMAf92asdkjoKXvzwFLxTZB1TusZVBwOUYe5jNLF4zCd7cgzjr4MT/9UKdT6BnPGvYzWMWNP+DM3td1zaatQxA72VTnNzaLqC2jyZYfjfNJ9725NOgxmBeNM3pUreJMxnRijmAa4kD1CsQnXJLLujEt1E9NUJPZRitE0EqWI+pFwFUQG+08WpiJ4OTxTCAJR9lpwK8w8YMSIAKHECf0gKXX8aASEnI1ZH5+CUYkrlKKk6TIkSsAxfbGEp65LElhrirGltyJMJSdYxUq5RUxxnFvGaTkUjZySIDdgAnedCWRV37JeKhj0mYQyT3+KhDWKrRk9xdkWrDSC59UIs8QtSZd9wI1eKx90UQopqINFw3NkkKAtIdL3j3SRY0dgA9Yj1tABzA4OwFSoBCjh7cuOTk1WFjhgz/gqJRmWwuHFnIRbwCJI8LAkMHEnY1UASNkxfcQaLBh0Y8XiOX7+los9jAJKKkl4AkoMzsUAlwOdOiM3Wb5FsRELsBIZ+5qLs06Lm4M5BkEt24Rx6OicpBCh4a1nwH7Fr6+8JE8g95Lbyh//AT2O/AAFScz1K2QDudNP0hdrSmSs3Jtlr2QVF+DQlgSSkRR6CicJv3HUOMB7zT8UMLjANiKt4WeYhygntWfeh1JvH3qZM3A1ebR9kYJEDNN89q7YBxLzDajeeJlYzvzB4zgbH5dwjQD/Scu+//uEpRGULyVAAlG+74eEnM35OX0KvqC6tSYcKNl9VcRPg4mvwFogQQ/1HzwAFpp2mOcX6cwRwc53XbdiouNxQREx5+sQ638A9AVzEtVw0n5yz84Gz2IBKjUBODARz+wRzAt3Cg13t8on/7l0EP8QQByGr8V3b5kGuWVBwu0oBRkilIsjE5CAyfIggu0iReAjCs4iX1Ui6U0Q14ARvIAAigEgrGEhW08C7AsIPdMCr+4jH5EC60gDHiIHnENwNukUFnNwMtyF6mdoYpgYIV8IJSogAsyHxmiIZyuApqiAUBEVy99Ya4QGpz2IeeoIYCl4dlJgYACIfe0imHkAD75YekgIIO4BYhVoh7CFwGYEIx8TrgsHLv9gtJ8Rp/4BCd4gztwCo1EQ1Zsv8t6VIaykQuCsIrCLcPi8iIkXA0wkABi1ICCHEAk8heH7EswCJG3bBDtiEV7iIMnnYU8tJSCVdxBGAR/MQgq1EuV1EAItFS6SeLfwgRAjAJJeAAOdGMapdzJINCflQqMbEpU7gx+AYm8BETqxEgwEEZpvgu9KZwB0MfSOhPs4eNnNApWOdIjiRu2TBetqFRm6IpSdgp3oGOlhIayVArPgEfIyEtwgUxnbJDSNIN6kguwTgxOQQl/NiPF9l1+WEeuLBegIAk0HIwA2B8F2mFREgnsfaJx1YtYGIAygY/UeIQSfIQZmcLvJWFIXEioCiGNchsIQkJR4NCodaUk/MNAjj/NFI5lVRZlVZ5lVjJM1QDM9bGXhfFWGDZNNlAMGFZlmKJc8JhlmqJNGMJXGv5luAYjmkJl2bZluyFNR7URUzzP7dEl8Bkl3PJOc3jOYI5O9bESIfzTH4ZSoDpB+YDDV1EH9ICmWlFO5G5QzlFD3S0mHXUmH1QSNbYDMgzGtZhmGeEmHp5HZvJmTLkmcI2O64imiVXGN6TPPZwOt9zUqzZmWjpmLDpKS1FJbXzSYiEUxdEnES1m+LjmlfDSDhlPmm1R1eTnFqzVEmTQBdkHtRJl8xpNbVjTdspQCKlNc6TNO40PIRhVazZnVRjTCWDG4xzSKOhLbkURNQTLGRUb/+Y/0Svo5quo0RHZEQCqpxxSZZWA1AUoky3GQ89ZDt0kUv32VKNA0QK2lD6EhETyk9w5Dyfs5qLyZ5RgzvHRBfYs6HAWSGraKEFVJnvSRcaQXo+pFGycolUQg85iTgEWqBuuT/101TSwj6lk0DleFI4mD7pA532w0kSFDo/CjoIdD485EdNZYmMlKM6epfemZnQCVNMI1IrCldWGjcgKjXJETntczoX1DEp5Uv42ThgGqZvM6aVxB+keUSIuUT78UmW1DxvCqdtI6dOw0kIuiBbZKb1kBhgtEvNpJha6qd4A6hNgzviQDLa1EdFhSnHoDSt9JyO+qi9+Zlls0IalD4UVP9BGWVJGvRJnSqmn/qaZNMdPaSfrzOf2TKR0bmqbgOp5Kmd2wNxvpIQvWibpdSnuBo2upo1m9Mr8nlIx+EcElSsrCqXvvmq0yJ+RkqO16AwZRR8twqtZ3OsmopKhTSjkSM7J6WbqNIrsdlI3so24FpILqWpAxSq89quY/OuiTNB32mvjNkHBAmqUiNECMqv/YqS0xo1pHOoAhBOBMub0gqwIRqvqtqwCoSvhVM/i0OxkmSxGjtNHNuxwfSxIPtKIjuy/fqwrmqyEuWaWdmyLvuyMBuzMmszXQkIknazOJuzllWz5jAJtKWzQBu00hUKvtWqwfVcQpu0SptbvnBdPFtMWgqCtEs7tVSrWtIydkY7dj9btVzbtZ5FtFiLssPltWRbtp31tEmZtgTCh4AQi5DgtmrLCHC7JzdCA4yGaWY7Wpm2WnurWpFWaZAVAQA7"

[[snippets]]
title = "Vue3のプロジェクト作成・実行"
description = "https://vuejs.org/guide/quick-start.html"
url = ""
code = """
npm init vue@latest
npm install
npm run dev
"""
thumbnail = ""

[[snippets]]
title = "blob2objectURL"
description = """

"""
url = "https://developer.mozilla.org/ja/docs/Web/API/URL/createObjectURL"
code = """
let url = URL.createObjectURL(blob);

"""
thumbnail = ""

[[snippets]]
title = "動的リソースのURL[vue3]"
description = """
viteコンパイラはsrcフォルダ内の静的URLの相対参照をよしなに解決してくれるが、動的参照は自分で解決する必要がある。

https://ja.vitejs.dev/guide/assets.html

"""
url = ""
code = """
<script setup>
function iconUrl(relativePath:string){
  return new URL(relativePath, window.location.href).href
}
</script>
<template>
<img :src="iconUrl('img/icon.png')" />
</template>
"""
thumbnail = ""

[[snippets]]
title = "３項演算子でnullの場合分け代入"
description = """
nullでなければ処理、nullなら別の値。
blob : nullableな変数
"""
url = ""
code = """
imageDataOriginal.value = blob ? await BlobToImageData(blob) : null;
"""
thumbnail = ""

[[snippets]]
title = "SFC+setupにおけるemitの定義"
code = """
const emit = defineEmits(['onChanged'])
function _emit(b64: string) {
  emit("onChanged", b64);
}
"""
