# snippets for html/css

[[tagGroup]]
name = "カテゴリ"
tags = "html,css,javascript,typescript,vue,XPath"

[[tagGroup]]
name = "操作"
tags = "移動,コピー,開く,作成,変更,削除"


[[snippets]]
title = "[html]FlexBox"
icon = "list-view"
description = """
●　使い方（※クラス名がflex_boxの場合）
```
<div class="flex_box">
    <div>アイテム１</div>
    <div>アイテム２</div>
</div>
```
"""
code = """
._{クラス名}_ {
    display: flex;
}
"""

[[snippets]]
title = "[vue]リンク先を動的に指定"
icon = "unknown"
description = """
:href=　でプロパティを動的に指定できる。
TSコードは " で囲む。
`?lang=${...}` はTSのテンプレートリテラルでクエリ文字列の作成。
"""
code = """
<a class="_{クラス名}_" :href="`?lang=${_{JS/TSコード}_}`">_{表示文字列}_</a>
"""

[[snippets]]
title = "idやclassで指定するXPath"
url = "http://aoproj.web.fc2.com/xpath/XPath_cheatsheets_v2.pdf"
code = """
# classで指定
//div[@class="hoge"] 

# idで指定
//*[@id=”hoge”]
"""



